-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- Leads Table
create table if not exists leads (
  id bigint generated by default as identity primary key,
  platform text not null,
  username text,
  profile_url text,
  post_text text not null,
  post_id text unique not null,
  matched_keyword text,
  intent_score int,
  intent_label text,
  contact_info text,
  detected_at timestamp with time zone default timezone('utc'::text, now()) not null,
  notified boolean default false
);

-- Logs Table
create table if not exists logs (
  id bigint generated by default as identity primary key,
  level text,
  message text,
  timestamp timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS Policies (Security)
alter table leads enable row level security;
alter table logs enable row level security;

-- Allow public read access (for Dashboard)
create policy "Public Read Leads" on leads for select using (true);
create policy "Public Read Logs" on logs for select using (true);

-- Allow anon insert access (for Agent using Anon Key)
create policy "Anon Insert Leads" on leads for insert with check (true);
create policy "Anon Insert Logs" on logs for insert with check (true);
create policy "Anon Update Leads" on leads for update using (true);
